### ISSUE TITLE
`be help` does not work

### ISSUE THREAD

**Issue by matthiasbeyer** [aaiyer/bugseverywhere#1]
output:

```
WARNING:root:unable to import libbe._version: No module named _version
Usage Error:
Unknown command 'html'
(No module named jinja2)
For usage information, try
  be help html
```

**Comment by aaiyer** [comment]
You need to use python2 to install this, python3 is not supported

**Comment by matthiasbeyer** [comment]
It is installed with python 2.7

**Comment by aaiyer** [comment]
Do a pip install jinja2

**Comment by matthiasbeyer** [comment]
Okay, my package manager installed jinja2 not properly, I fixed this issue.

The 

```
WARNING:root:unable to import libbe._version: No module named _version
```

remains, though.

**Comment by aaiyer** [comment]
You need to install it by running python setup.py that will generate the
_version.py
